/**
 * Emits idempotent SQL to seed the MBAround school universe.
 *
 * Run:  npm run seed:sql > seed.sql
 * Then paste the output into the Supabase SQL editor.
 *
 * Emitting SQL rather than writing over the network is deliberate: seeding
 * needs the service role key, which bypasses RLS. Producing a script the
 * owner reviews and runs themselves keeps that key out of this tool entirely.
 *
 * WHAT THIS DOES NOT DO
 * ---------------------
 * It never writes a deadline, a decision date or an application round. Those
 * come only from official admissions pages via collect-deadlines.ts. Seeding
 * establishes WHICH schools exist; announcing WHEN their rounds fall is a
 * separate, evidence-bearing step.
 *
 * Schools are seeded is_published = true (they are public institutions whose
 * existence is not in doubt) but is_verified = false, because "verified" in
 * MBAround means a human checked this record against its official source.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface ProgramSeed {
  name: string;
  programType: string;
  durationMonths: number | null;
}

interface SchoolSeed {
  name: string;
  shortName: string | null;
  slug: string;
  country: string;
  region: string;
  state: string | null;
  city: string;
  websiteUrl: string | null;
  admissionsUrl: string | null;
  programs: ProgramSeed[];
}

/** Single-quote escaping for SQL literals; null stays a real NULL. */
function lit(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') return String(value);
  return "'" + value.replace(/'/g, "''") + "'";
}

/** Mirrors the schools_slug_format CHECK constraint in migration 0001. */
function slugify(input: string): string {
  return input
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const file = path.join(__dirname, 'schools.json');
const { schools } = JSON.parse(readFileSync(file, 'utf8')) as {
  schools: SchoolSeed[];
};

const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

// Fail before emitting anything rather than producing SQL the database will
// reject halfway through.
const seen = new Set<string>();
for (const s of schools) {
  if (!SLUG_RE.test(s.slug)) {
    throw new Error(`Invalid slug "${s.slug}" for ${s.name}`);
  }
  if (seen.has(s.slug)) throw new Error(`Duplicate slug: ${s.slug}`);
  seen.add(s.slug);
  if (!s.programs?.length) {
    throw new Error(`${s.name} has no programmes`);
  }
}

const out: string[] = [];

out.push('-- MBAround school universe seed');
out.push('-- Generated by scripts/data/emit-seed-sql.ts - do not edit by hand.');
out.push('--');
out.push('-- Contains NO deadlines, decision dates or application rounds.');
out.push('-- Those are collected from official admissions pages only.');
out.push('--');
out.push(`-- Schools: ${schools.length}`);
out.push('');
out.push('begin;');
out.push('');

for (const s of schools) {
  out.push(`-- ${s.name}`);
  out.push(`insert into schools (name, slug, short_name, country, region, state, city, website_url, admissions_url, is_published, is_verified, status)`);
  out.push(`values (${lit(s.name)}, ${lit(s.slug)}, ${lit(s.shortName)}, ${lit(s.country)}, ${lit(s.region)}, ${lit(s.state)}, ${lit(s.city)}, ${lit(s.websiteUrl)}, ${lit(s.admissionsUrl)}, true, false, 'NEEDS_REVIEW')`);
  out.push(`on conflict (slug) do update set`);
  out.push(`  name = excluded.name,`);
  out.push(`  short_name = excluded.short_name,`);
  out.push(`  country = excluded.country,`);
  out.push(`  region = excluded.region,`);
  out.push(`  state = excluded.state,`);
  out.push(`  city = excluded.city,`);
  out.push(`  website_url = excluded.website_url,`);
  out.push(`  admissions_url = excluded.admissions_url;`);
  out.push('');

  for (const [i, p] of s.programs.entries()) {
    const pSlug = slugify(p.name);
    out.push(`insert into programs (school_id, name, slug, program_type, duration_months, display_order, is_published, is_verified, status)`);
    out.push(`select id, ${lit(p.name)}, ${lit(pSlug)}, ${lit(p.programType)}, ${lit(p.durationMonths)}, ${i}, true, false, 'NEEDS_REVIEW'`);
    out.push(`from schools where slug = ${lit(s.slug)}`);
    out.push(`on conflict (school_id, slug) do update set`);
    out.push(`  name = excluded.name,`);
    out.push(`  program_type = excluded.program_type,`);
    out.push(`  duration_months = excluded.duration_months,`);
    out.push(`  display_order = excluded.display_order;`);
    out.push('');
  }
}

out.push('commit;');
out.push('');
out.push('-- Verify:');
out.push('--   select count(*) from schools;   -- expect ' + schools.length);
out.push('--   select count(*) from programs;');
out.push('--   select count(*) from application_rounds;  -- expect 0');

console.log(out.join('\n'));
