/**
 * Emits SQL for the 2026-27 application rounds in deadlines-2026-27.ts.
 *
 * Run: npx tsx scripts/data/emit-rounds-sql.ts > rounds.sql
 *
 * The emitted SQL is deliberately conservative:
 *
 *  - It resolves cycles by joining schools -> programs -> application_cycles
 *    on slug and programme name. No UUIDs are hardcoded, so it stays correct
 *    if the database is rebuilt.
 *
 *  - It is idempotent. `on conflict (application_cycle_id, name)` means
 *    running it twice updates rather than duplicates, so a partial failure
 *    can simply be re-run.
 *
 *  - It fails loudly. If a slug or programme name does not resolve, the
 *    statement raises instead of silently inserting nothing - a school
 *    quietly missing its deadlines is worse than an error, because absence
 *    looks exactly like "not announced yet" and nobody investigates.
 *
 *  - Nothing is emitted as is_verified. These dates were typed in by hand,
 *    not read off an official page with a URL recorded. Every row lands as
 *    NEEDS_REVIEW, which is what "someone typed this in" honestly looks like.
 *
 *  - is_announced is true only where a real deadline exists, matching the
 *    rounds_unannounced_has_no_dates constraint.
 */
import { CYCLES, CYCLE_NAME, EXCLUDED, SOURCE_NAME } from './deadlines-2026-27.js';

/** Single-quote escaping for SQL literals; null stays a real NULL. */
function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null';
  return "'" + value.replace(/'/g, "''") + "'";
}

const out: string[] = [];

let roundCount = 0;
let datedCount = 0;
for (const c of CYCLES) {
  for (const r of c.rounds) {
    roundCount++;
    if (r.deadline) datedCount++;
  }
}

out.push('-- MBAround: 2026-27 application rounds');
out.push('--');
out.push('-- Generated by scripts/data/emit-rounds-sql.ts. Do not edit by hand;');
out.push('-- edit scripts/data/deadlines-2026-27.ts and re-run.');
out.push('--');
out.push('-- Provenance: user-supplied compilation, NOT machine-read from official');
out.push('-- pages. Every row is inserted as NEEDS_REVIEW with no source_url and');
out.push('-- is_verified = false. Estimated dates from the source were excluded.');
out.push('--');
out.push('-- Idempotent: re-running updates existing rounds instead of duplicating.');
out.push('--');
out.push(`-- Cycles: ${CYCLES.length}`);
out.push(`-- Rounds: ${roundCount} (${datedCount} dated, ${roundCount - datedCount} undated)`);
out.push('--');
out.push('-- Excluded from this import, and why:');
for (const e of EXCLUDED) out.push(`--   ${e.label}: ${e.reason}`);
out.push('');
out.push('begin;');
out.push('');

for (const cycle of CYCLES) {
  const label = `${cycle.schoolSlug} / ${cycle.programName}`;
  out.push(`-- ${label}`);
  out.push('with target as (');
  out.push('  select ac.id');
  out.push('  from application_cycles ac');
  out.push('  join programs p on p.id = ac.program_id');
  out.push('  join schools s on s.id = p.school_id');
  out.push(`  where s.slug = ${lit(cycle.schoolSlug)}`);
  out.push(`    and p.name = ${lit(cycle.programName)}`);
  out.push(`    and ac.cycle_name = ${lit(CYCLE_NAME)}`);
  out.push('),');
  out.push('data(name, deadline, decision_date, notes, display_order) as (values');

  const values = cycle.rounds.map((r, i) => {
    const notes = [cycle.intakeNote, r.notes].filter(Boolean).join(' ');
    const deadline = r.deadline ? `${lit(r.deadline)}::date` : 'null::date';
    const decision = r.decisionDate ? `${lit(r.decisionDate)}::date` : 'null::date';
    const noteLit = notes ? lit(notes) : 'null::text';
    return `  (${lit(r.name)}, ${deadline}, ${decision}, ${noteLit}, ${i})`;
  });
  out.push(values.join(',\n'));
  out.push(')');
  out.push('insert into application_rounds (');
  out.push('  application_cycle_id, name, deadline, decision_date, notes,');
  out.push('  is_announced, is_verified, status, source_name, display_order');
  out.push(')');
  out.push('select');
  out.push('  target.id, data.name, data.deadline, data.decision_date, data.notes,');
  out.push('  data.deadline is not null,');
  out.push('  false,');
  out.push("  'NEEDS_REVIEW'::record_status,");
  out.push(`  ${lit(SOURCE_NAME)},`);
  out.push('  data.display_order');
  out.push('from data cross join target');
  out.push('on conflict (application_cycle_id, name) do update set');
  out.push('  deadline      = excluded.deadline,');
  out.push('  decision_date = excluded.decision_date,');
  out.push('  notes         = excluded.notes,');
  out.push('  is_announced  = excluded.is_announced,');
  out.push('  display_order = excluded.display_order,');
  out.push('  source_name   = excluded.source_name;');
  out.push('');

  /*
    A cross join against an empty `target` inserts zero rows and reports
    success. That is the failure mode this whole file exists to avoid, so
    each block asserts the cycle resolved before moving on.
  */
  out.push('do $$ begin');
  out.push('  if not exists (');
  out.push('    select 1 from application_cycles ac');
  out.push('    join programs p on p.id = ac.program_id');
  out.push('    join schools s on s.id = p.school_id');
  out.push(`    where s.slug = ${lit(cycle.schoolSlug)}`);
  out.push(`      and p.name = ${lit(cycle.programName)}`);
  out.push(`      and ac.cycle_name = ${lit(CYCLE_NAME)}`);
  out.push('  ) then');
  out.push(`    raise exception 'cycle not found: ${label.replace(/'/g, "''")}';`);
  out.push('  end if;');
  out.push('end $$;');
  out.push('');
}

out.push('commit;');
out.push('');
out.push('-- Verification. Expect the counts in the header above, and zero verified.');
out.push('select');
out.push('  count(*)                                as rounds_total,');
out.push('  count(deadline)                         as rounds_dated,');
out.push('  count(*) filter (where is_verified)     as verified_must_be_zero,');
out.push('  count(*) filter (where is_announced and deadline is null)');
out.push('                                          as announced_undated_must_be_zero,');
out.push('  count(*) filter (where deadline is not null and not is_announced)');
out.push('                                          as dated_unannounced_must_be_zero');
out.push('from application_rounds;');
out.push('');

process.stdout.write(out.join('\n'));
